name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter=1.0.0
  - jupyterlab=4.0.2
  - numpy=1.24.4
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - pytest=7.4.0
  - requests=2.31.0
  - dvc=3.4.0
  - dvclive=2.12.1
  - fastapi=0.63.0
  - uvicorn=0.22.0
  - gunicorn=20.1.0
  - pip=23.1.2
