stages:
  prepare:
    cmd: python prepare.py --input_artifact ../data/census.csv --remote_storage census_storage
      --output_artifact ../data/cleaned-data.csv --min_fnlgt 12000.0 --max_fnlgt 600000.0
      --min_capital_loss 0 --max_capital_loss 250 --min_capital_gain 0 --max_capital_gain
      15000
    deps:
    - ../data/census.csv
    - prepare.py
    outs:
    - ../data/cleaned-data.csv
  split:
    cmd: python splitting_data.py --input_artifact ../data/cleaned-data.csv --remote_storage
      census_storage --test_size 0.2 --random_state 42 --train_path ../data/train-data.csv
      --test_path ../data/test-data.csv
    deps:
    - ../data/cleaned-data.csv
    - splitting_data.py
    outs:
    - ../data/test-data.csv
    - ../data/train-data.csv
  train:
    cmd: python train_model.py --input_artifact ../data/train-data.csv --remote_storage
      census_storage --random_state 42 --model_config model_config.json --output_artifact
      ../model/rfmodel.pkl
    deps:
    - ../data/train-data.csv
    - train_model.py
    outs:
    - ../model/rfmodel.pkl
